# Generated by Django 3.2.6 on 2022-04-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Inputs',
            },
        ),
        migrations.CreateModel(
            name='WasteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Waste Products',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('inputs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managemenet.inputs')),
                ('waste_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managemenet.wasteproducts')),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
    ]
