# Generated by Django 3.2.5 on 2022-05-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0002_alter_wasteproduct_reuse_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteproduct',
            name='reuse_plan',
            field=models.CharField(choices=[('Donate', 'Donate'), ('Sell', 'Sell'), ('Safe Dump', 'Safe Dump'), ('Reuse', 'Reuse')], default='Donate', max_length=20, verbose_name='Recyle Plan'),
        ),
        migrations.CreateModel(
            name='waste_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default='#INV001', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('companyA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_invoices', to='managemenet.industry')),
                ('companyB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managemenet.industry')),
            ],
            options={
                'verbose_name_plural': 'invoices',
                'db_table': 'invoices',
                'ordering': ['-date'],
            },
        ),
    ]
