# Generated by Django 3.2.5 on 2022-05-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0003_auto_20220523_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste_invoice',
            name='price',
        ),
    ]
