# Generated by Django 3.2.5 on 2022-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0006_auto_20220524_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='category',
        ),
        migrations.AlterField(
            model_name='wasteproduct',
            name='category',
            field=models.CharField(choices=[('Solid Waste', 'Solid Waste'), ('Liquid Waste', 'Liquid Waste'), ('Reusable Waste', 'Reusable Waste'), ('Hazardous Waste', 'Hazardous Waste')], default='Solid Waste', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
