# Generated by Django 3.2.5 on 2022-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0007_auto_20220524_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteproduct',
            name='reusable',
        ),
        migrations.RemoveField(
            model_name='wasteproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
