# Generated by Django 3.2.5 on 2022-05-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0008_auto_20220524_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteproduct',
            name='mass',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
