# Generated by Django 3.2.5 on 2022-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0011_remove_wasteproduct_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='waste_invoice',
            name='transportation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
