# Generated by Django 3.2.5 on 2022-05-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0014_auto_20220525_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_invoice',
            name='waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='managemenet.wasteproduct'),
        ),
    ]
