# Generated by Django 3.2.5 on 2022-05-25 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managemenet', '0015_waste_invoice_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastes_invoice', to=settings.AUTH_USER_MODEL),
        ),
    ]
