# Generated by Django 3.2.5 on 2022-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0016_waste_invoice_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='sys_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_mail', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email & SMS Settings',
                'db_table': 'sys_settings',
            },
        ),
    ]
