# Generated by Django 3.2.5 on 2022-06-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managemenet', '0017_sys_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sys_settings',
            new_name='Notification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notification Settings'},
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification_settings',
        ),
    ]
